export const GET_BROKEN_LINKS = "GET_BROKEN_LINKS";
export const GET_DUPLICATE_LINKS = "GET_DUPLICATE_LINKS";
export const GET_DUPLICATE_LINKS_BY_AMOUNT = "GET_DUPLICATE_LINKS_BY_AMOUNT";
export const FILTER_BROKEN_BOOKMARK = "FILTER_BROKEN_BOOKMARK";
export const RESET_FILTER_BROKEN_BOOKMARK = "RESET_FILTER_BROKEN_BOOKMARK";