// export const GET_AUTHORAIZATION_TOKEN = "GET_AUTHORAIZATION_TOKEN";
// export const GET_WEBSITE_DETAILS = "GET_WEBSITE_DETAILS";
export const SET_LOCALE = "SET_LOCALE";
export const SET_SHARE_TOKEN = "SET_SHARE_TOKEN";
export const SET_DASHBOARD_USER = "SET_DASHBOARD_USER";
export const SET_DASHBOARD_CONFIG = "SET_DASHBOARD_CONFIG";
export const SET_DATE_RANGE = "SET_DATE_RANGE";