export const FETCH_COLLECTION_WISE_COUNTS = "FETCH_COLLECTION_WISE_COUNTS"
export const UPDATE_COLLECTION = "UPDATE_COLLECTION"
export const MOVE_COLLECTION = "MOVE_COLLECTION"
export const MOVE_COLLECTION_SHARED = "MOVE_COLLECTION_SHARED"
export const CLEAR_COLLECTIONS = "CLEAR_COLLECTIONS";
export const RESET_SHARED_COLLECTIONS = "RESET_SHARED_COLLECTIONS"
export const FETCH_COLLECTION = 'FETCH_COLLECTION'
export const DELETE_COVER_S3_LINK = "DELETE_COVER_S3_LINK";

export const GET_USER_COLLECTIONS = 'GET_USER_COLLECTIONS'
export const ADD_COLLECTION = 'ADD_COLLECTION'
export const ADD_COLLECTION_RESET = 'ADD_COLLECTION_RESET'
export const BULK_SELECT_EDIT = 'BULK_SELECT_EDIT'
export const UPDATE_BULK_BOOKMARK_STATE = "UPDATE_BULK_BOOKMARK_STATE"
export const DELETE_BULK_BOOKMARK_STATE = "DELETE_BULK_BOOKMARK_STATE"
export const DELETE_BULK_BOOKMARK_STATE_SHARED_COLLECTION = "DELETE_BULK_BOOKMARK_STATE_SHARED_COLLECTION"
export const UPDATE_BULK_BOOKMARK_STATE_SHARED_COLLECTION = "UPDATE_BULK_BOOKMARK_STATE_SHARED_COLLECTION"
export const GET_SINGLE_BOOKMARK_GEM = "GET_SINGLE_BOOKMARK_GEM"
export const MOVE_GEM_TO_SHARED_COLLECTION = "MOVE_GEM_TO_SHARED_COLLECTION"
export const REMOVE_GEM_FROM_COLLECTION = "REMOVE_GEM_FROM_COLLECTION"
export const UPDATE_BOOKMARK_EXISTING_COLLECTION = "UPDATE_BOOKMARK_EXISTING_COLLECTION"
export const UPDATE_GEM = "UPDATE_GEM"
export const UPLOAD_BOOKMARK_COVER = "UPLOAD_BOOKMARK_COVER"
export const UPLOAD_SCREENSHOTS = "UPLOAD_SCREENSHOTS"
export const DELETE_ALL_COLLECTIONS = "DELETE_ALL_COLLECTIONS"
export const DELETE_IMG_FROM_S3 = 'DELETE_IMG_FROM_S3'
export const GET_BOOKMARK_IN_COLLECTION = "GET_BOOKMARK_IN_COLLECTION"
export const GET_CUSTOM_FIELDS = "GET_CUSTOM_FIELDS"
export const GET_SHARED_COLLECTIONS = "GET_SHARED_COLLECTIONS"
export const UPDATE_COLLECTION_PAGE_CONFIG = "UPDATE_COLLECTION_PAGE_CONFIG"
export const UPDATE_CUSTOM_FIELDS_PROPERTY = "UPDATE_CUSTOM_FIELDS_PROPERTY"
export const DELETE_CUSTOM_FIELDS_PROPERTY = "DELETE_CUSTOM_FIELDS_PROPERTY"
export const CREATE_CUSTOM_FIELDS = "CREATE_CUSTOM_FIELDS"
export const UPLOAD_ICONS = "UPLOAD_ICONS"
export const UPLOAD_UNSPLASH = "UPLOAD_UNSPLASH"
export const UPLOAD_COVER_S3_LINK = "UPLOAD_COVER_S3_LINK"
export const UPLOAD_UNSPLASH_IMAGE_IN_S3 = "UPLOAD_UNSPLASH_IMAGE_IN_S3"
export const COLLECTION_FILTER_BOOKMARK = "COLLECTION_FILTER_BOOKMARK"
export const RESET_COLLECTION_FILTER_BOOKMARK = "RESET_COLLECTION_FILTER_BOOKMARK"
export const GET_SINGLE_COLLECTION = "GET_SINGLE_COLLECTION"
export const CREATE_COLLECTION = "CREATE_COLLECTION"
export const COLLECTION_MOVE = "COLLECTION_MOVE"
export const SHARED_COLLECTION_MOVE = "SHARED_COLLECTION_MOVE"
export const DELETE_COLLECTION = "DELETE_COLLECTION"
export const UPDATE_SHARED_COLLECTION = "UPDATE_SHARED_COLLECTION"

export const SET_PASSWORD_PUBLIC_LINK = "SET_PASSWORD_PUBLIC_LINK"
export const DISABLE_PUBLIC_LINK = "DISABLE_PUBLIC_LINK"
export const CHECK_COLLECTION_VIA_PUBLIC = "CHECK_COLLECTION_VIA_PUBLIC"
export const SHARE_COLLECTION_VIA_PUBLIC = "SHARE_COLLECTION_VIA_PUBLIC"
export const CHANGE_SECURITY_LINK = "CHANGE_SECURITY_LINK"
export const REMOVE_ACCESS_LINK = "REMOVE_ACCESS_LINK"
export const CHECK_COLLECTION_VIA_LINK = "CHECK_COLLECTION_VIA_LINK"
export const SHARE_COLLECTION_VIA_LINK = "SHARE_COLLECTION_VIA_LINK"
export const CHANGE_SECURITY_EMAIL = "CHANGE_SECURITY_EMAIL"
export const REMOVE_ACCESS_EMAIL = "REMOVE_ACCESS_EMAIL"
export const UPDATE_UNREGISTERED_USER = "UPDATE_UNREGISTERED_USER"
export const CHECK_USER_REGISTERED = "CHECK_USER_REGISTERED"
export const CHECK_COLLECTION_EXPIRATION = "CHECK_COLLECTION_EXPIRATION"
export const SHARE_COLLECTION_VIA_EMAIL = "SHARE_COLLECTION_VIA_EMAIL"
export const REMOVE_SHARED_COLLECTION = "REMOVE_SHARED_COLLECTION"
export const GET_PUBLIC_SHARE_COLLECTION = "GET_PUBLIC_SHARE_COLLECTION"
export const ADD_GEM_TO_SHARED_COLLECTION = "ADD_GEM_TO_SHARED_COLLECTION"
export const LIKE_GEM = "LIKE_GEM"
export const GET_RANDOM_BOOKMARK_GEMS = "GET_RANDOM_BOOKMARK_GEMS"
export const RESET_COLLECTION_WISE_COUNTS = "RESET_COLLECTION_WISE_COUNTS"
export const SHARE_COLLECTION_VIA_EMAIL_GROUP = "SHARE_COLLECTION_VIA_EMAIL_GROUP"

export const UPDATE_COLLECTION_WISE_COUNTS = "UPDATE_COLLECTION_WISE_COUNTS"
export const REDUCE_COLLECTION_WISE_COUNTS = "REDUCE_COLLECTION_WISE_COUNTS"
export const MOVE_TO_ROOT = "MOVE_TO_ROOT"
export const ADD_COLLECTION_COUNT = "ADD_COLLECTION_COUNT"
export const GET_BOOKMARK_IN_BIO= "GET_BOOKMARK_IN_BIO"
export const COPY_COLLECTION= "COPY_COLLECTION"

// SEO DETAILS
export const UPDATE_COLLECTION_SEO_DETAILS = "UPDATE_COLLECTION_SEO_DETAILS"
//Shared Collection Subfolder

export const GET_PENDING_GEMS = "GET_PENDING_GEMS"
export const APPROVE_REJECT_GEM = "APPROVE_REJECT_GEM"
export const GET_RESOLVED_GEMS = "GET_RESOLVED_GEMS"
export const UPDATE_COUNT_PUBLIC_ADDED_GEM = "UPDATE_COUNT_PUBLIC_ADDED_GEM"
export const GET_SUB_COLLECTIONS = "GET_SUB_COLLECTIONS"
export const SUB_COLLECTIONS_PAGE = "SUB_COLLECTIONS_PAGE"
export const GET_PARENT_PUBLIC_COLLECTION_IN_PROFILE = "GET_PARENT_PUBLIC_COLLECTION_IN_PROFILE"
export const SET_PROFILE_SUB_COLLECTION = "SET_PROFILE_SUB_COLLECTION"
export const SET_PUBLIC_PROFILE_SUB_COLLECTION = "SET_PUBLIC_PROFILE_SUB_COLLECTION"
export const GET_PUBLIC_COLLECTION_SUB_COLLECTION = "GET_PUBLIC_COLLECTION_SUB_COLLECTION"
export const GET_PUBLIC_COLLECTION_CATEGORY = "GET_PUBLIC_COLLECTION_CATEGORY"
export const GET_PUBLIC_COLLECTION_TAGS = "GET_PUBLIC_COLLECTION_TAGS"
export const GET_PUBLIC_COLLECTION_FILTERS_GEMS = "GET_PUBLIC_COLLECTION_FILTERS_GEMS"
export const GET_PUBLIC_COLLECTION_TAGS_GEMS = "GET_PUBLIC_COLLECTION_TAGS_GEMS"

export const DELETE_EMPTY_COLLECTIONS = "DELETE_EMPTY_COLLECTIONS"

export const UPDATE_GROUP_ACCESS = "UPDATE_GROUP_ACCESS"

export const CHECK_IS_PUBLIC_COLLECTION = "CHECK_IS_PUBLIC_COLLECTION"
export const CHECK_IS_PUBLIC_GEM = "CHECK_IS_PUBLIC_GEM"

export const GET_FOLLOWED_BY_ME_COLLECTION = "GET_FOLLOWED_BY_ME_COLLECTION"
export const FOLLOW_COLLECTION = "FOLLOW_COLLECTION"
export const UNFOLLOW_COLLECTION = "UNFOLLOW_COLLECTION"

export const CONFIG_LIMIT_FOR_COLLECTION = "CONFIG_LIMIT_FOR_COLLECTION"
export const CONFIG_COLLECTIONS = "CONFIG_COLLECTIONS"

export const EXPORT_COLLECTION = "EXPORT_COLLECTION"
export const ADD_SUB_COLLECTION_DATA = "ADD_SUB_COLLECTION_DATA"
export const REMOVE_SHARE_WITH_ME_COLLECTION = "REMOVE_SHARE_WITH_ME_COLLECTION"

export const UPLOAD_CSV_TEXT_LINKS = "UPLOAD_CSV_TEXT_LINKS"
export const ADD_IMPORT_COLLECTION = "ADD_IMPORT_COLLECTION"
export const IMPORT_GEMS_WITH_ICON = "IMPORT_GEMS_WITH_ICON"
export const ADD_COLLECTION_ACTIVITY = "ADD_COLLECTION_ACTIVITY"
export const UPDATE_COLLECTION_DATA_FOR_IMPORT = "UPDATE_COLLECTION_DATA_FOR_IMPORT"
export const GET_COLLECTION_BY_ID = "GET_COLLECTION_BY_ID"
export const GET_RELATED_COLLECTION = "GET_RELATED_COLLECTION";