export const GET_ALL_BOOKMARK = "GET_ALL_BOOKMARK";
export const GET_ALL_BOOKMARK_BY_AMOUNT = "GET_ALL_BOOKMARK_BY_AMOUNT";
export const GET_ALL_BOOKMARK_BY_USERID = "GET_ALL_BOOKMARK_BY_USERID";
export const GET_BOOKMARK_BY_COLLECTION = "GET_BOOKMARK_BY_COLLECTION";
export const CHANGE_BOOKMARK_TO_DIFFERENT_COLLECTION = "CHANGE_BOOKMARK_TO_DIFFERENT_COLLECTION";
export const DELETE_BOOKMARK = "DELETE_BOOKMARK";
export const BULK_DELETE_BOOKMARK = "BULK_DELETE_BOOKMARK";
export const GET_BOOKMARK_BY_FILTERS = "GET_BOOKMARK_BY_FILTERS";
export const GET_BOOKMARK_BY_FILTERS_AND_AMOUNT = "GET_BOOKMARK_BY_FILTERS_AND_AMOUNT";
//update highlight
export const EXTRACT_IMAGE_TEXT = 'EXTRACT_IMAGE_TEXT'

export const UPDATE_BOOKMARK_FILTERS_CONFIG = "UPDATE_BOOKMARK_FILTERS_CONFIG";
export const GROUP_BY = "GROUP_BY";
export const SUB_GROUP_BY = "SUB_GROUP_BY";
export const RESET_GROUP_BY = 'RESET_GROUP_BY'
export const RESET_SUB_GROUP_BY = 'RESET_SUB_GROUP_BY'

export const GROUP_BY_FILTER_PAGE = "GROUP_BY_FILTER_PAGE";
export const SUB_GROUP_BY_FILTER_PAGE = "SUB_GROUP_BY_FILTER_PAGE";
export const RESET_GROUP_BY_FILTER_PAGE = 'RESET_GROUP_BY_FILTER_PAGE'
export const RESET_SUB_GROUP_BY_FILTER_PAGE = 'RESET_SUB_GROUP_BY_FILTER_PAGE'

export const GET_BOOK_DETAILS = "GET_BOOK_DETAILS";
export const GET_PLATFORM_PROFILE = "GET_PLATFORM_PROFILE";
export const UPDATE_BROKEN_DUPLICATE_FILTERS_CONFIG = "UPDATE_BROKEN_DUPLICATE_FILTERS_CONFIG";
export const FILTER_BOOKMARK = "FILTER_BOOKMARK";
export const RESET_FILTER_BOOKMARK = "RESET_FILTER_BOOKMARK";
export const FILTER_PAGE_BOOKMARK = "FILTER_PAGE_BOOKMARK";
export const RESET_FILTER_PAGE_BOOKMARK = "RESET_FILTER_PAGE_BOOKMARK";
export const SEARCH_BOOKMARK = "SEARCH_BOOKMARK";

export const RESET_EXISTING_GEM = "RESET_EXISTING_GEM"

export const RESET_FILTERED_BOOKMARKS_DATA = "RESET_FILTERED_BOOKMARKS_DATA"
export const SEARCH_BOOKS = 'SEARCH_BOOKS'
export const CREATE_BOOK_GEM = 'CREATE_BOOK_GEM'
export const SEARCH_MOVIES = 'SEARCH_MOVIES'
export const CREATE_MOVIE_GEM = 'CREATE_MOVIE_GEM'

export const ADD_GEM = 'ADD_GEM'
export const UPLOAD_PDF = 'UPLOAD_PDF'
export const CREATE_AUDIO = 'CREATE_AUDIO'
export const CREATE_VIDEO = 'CREATE_VIDEO'
export const ADD_IMAGE = 'ADD_IMAGE'
export const ADD_CODE = 'ADD_CODE'
export const FILTER_PROFILE_PAGE_BOOKMARK = 'FILTER_PROFILE_PAGE_BOOKMARK'
export const SAVE_OTHER_GEM_IN_COLLECTION = 'SAVE_OTHER_GEM_IN_COLLECTION'
export const SAVE_SOCIAL_PROFILE_IN_CACHE = 'SAVE_SOCIAL_PROFILE_IN_CACHE'
export const GET_PAGE_CONFIG = 'GET_PAGE_CONFIG'
export const SAVE_PAGE_CONFIG = 'SAVE_PAGE_CONFIG'
export const GEM_ADDED = 'GEM_ADDED'
export const GET_BOOKMARK_DETAILS_MICROLINK = 'GET_BOOKMARK_DETAILS_MICROLINK'
export const FETCH_TEXT_FROM_AUDIO = 'FETCH_TEXT_FROM_AUDIO'

export const ADD_GEM_PUBLIC = 'ADD_GEM_PUBLIC'
export const UPLOAD_PDF_PUBLIC = 'UPLOAD_PDF_PUBLIC'
export const CREATE_AUDIO_PUBLIC = 'CREATE_AUDIO_PUBLIC'
export const CREATE_VIDEO_PUBLIC = 'CREATE_VIDEO_PUBLIC'
export const ADD_IMAGE_PUBLIC = 'ADD_IMAGE_PUBLIC'
export const ADD_CODE_PUBLIC = 'ADD_CODE_PUBLIC'
export const UPLOAD_ALL_FILE_TYPE = 'UPLOAD_ALL_FILE_TYPE'
export const GET_TEXT_FROM_IMAGE = 'GET_TEXT_FROM_IMAGE'
export const GET_PLATFORM_TYPE = "GET_PLATFORM_TYPE";