// GENERATED BY THE HUGEICONS PRO NPM CLI hugeicons-pro.
// DO NOT EDIT. CHANGES MAY BE OVERWRITTEN.
// FOR LICENSED USE ONLY.
//
// https://hugeicons.com
// https://hugeicons.com/license-agreement

import React from "react"

export function Cancel01Icon(props) {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path d="M19 5L5 19M5 5L19 19" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}
