export const GET_ALL_GROUPS = "GET_ALL_GROUPS";
export const GET_GROUP = "GET_GROUP";
export const EDIT_GROUP = "EDIT_GROUP";
export const CREATE_GROUP = "CREATE_GROUP"
export const DELETE_GROUP = "DELETE_GROUP"
export const GET_PUBLIC_USERS = "GET_PUBLIC_USERS"
export const FIND_MEMBER_EXIST = "FIND_MEMBER_EXIST"
export const GET_ALL_REGISTERD_USERS = "GET_ALL_REGISTERD_USERS"
