export const GET_RAINDROP_DATA  = 'GET_RAINDROP_DATA'
export const SYNC_RAINDROP_DATA = 'SYNC_RAINDROP_DATA'
export const SYNC_RAINDROP_HIGHLIGHTS = 'SYNC_RAINDROP_HIGHLIGHTS'
export const GET_RAINDROP_ACCESS_TOKEN = "GET_RAINDROP_ACCESS_TOKEN"
export const UPLOAD_RAINDROP_HIGHLIGHTS = "UPLOAD_RAINDROP_HIGHLIGHTS"