export const ADD_TAG = "ADD_TAG"
export const FETCH_TAGS_WITH_GEM_COUNTS = "FETCH_TAGS_WITH_GEM_COUNTS"
export const MOVE_TAG = "MOVE_TAG"
export const CLEAR_ALL_TAGS = 'CLEAR_ALL_TAGS'

export const UPDATE_ADD_NEW_GEM_TAG = "UPDATE_ADD_NEW_GEM_TAG"
export const REMOVE_GEM_FROM_TAG = "REMOVE_GEM_FROM_TAG"

export const GET_GEMS_IN_TAGS = "GET_GEMS_IN_TAGS"
export const TAG_FILTER_BOOKMARK = 'TAG_FILTER_BOOKMARK'
export const RESET_TAG_FILTER_BOOKMARK = 'RESET_TAG_FILTER_BOOKMARK'
export const UPLOAD_ICONS_TAG = 'UPLOAD_ICONS_TAG'
export const UPLOAD_UNSPLASH_IMAGE_IN_S3_TAG = 'UPLOAD_UNSPLASH_IMAGE_IN_S3_TAG'
export const UPLOAD_COVER_S3_LINK_TAG = 'UPLOAD_COVER_S3_LINK_TAG'
export const UPDATE_CONFIG_TAG = 'UPDATE_CONFIG_TAG'
export const UPDATE_TAG = 'UPDATE_TAG'
export const SUGGESTED_TAG_COLORS = 'SUGGESTED_TAG_COLORS'
export const DELETE_TAG = 'DELETE_TAG'
export const MOVE_TO_ROOT_TAG = 'MOVE_TO_ROOT_TAG'
export const ADD_TAG_COUNT = 'ADD_TAG_COUNT'
//email
export const GET_SHARED_TAGS = "GET_SHARED_TAGS"
export const RESET_SHARED_TAGS = "RESET_SHARED_TAGS"
export const SHARE_TAG_VIA_EMAIL = "SHARE_TAG_VIA_EMAIL"
export const CHECK_TAG_EXPIRATION = "CHECK_TAG_EXPIRATION"
export const SHARE_TAG_VIA_LINK = "SHARE_TAG_VIA_LINK"
export const CHECK_TAG_VIA_LINK = "CHECK_TAG_VIA_LINK"
export const GET_PUBLIC_SHARE_TAG = "GET_PUBLIC_SHARE_TAG"
export const GET_SINGLE_TAG_DETAILS = "GET_SINGLE_TAG_DETAILS"
export const GET_PUBLIC_SHARED_TAGS = "GET_PUBLIC_SHARED_TAGS"
export const CHANGE_SECURITY_EMAIL = "CHANGE_SECURITY_EMAIL"
export const REMOVE_ACCESS_EMAIL = "REMOVE_ACCESS_EMAIL"
export const REMOVE_SHARED_TAG = "REMOVE_SHARED_TAG"
export const REMOVE_ACCESS_LINK = "REMOVE_ACCESS_LINK"
export const CHANGE_SECURITY_LINK = "CHANGE_SECURITY_LINK"
export const SHARE_TAG_VIA_PUBLIC = "SHARE_TAG_VIA_PUBLIC"
export const CHECK_TAG_VIA_PUBLIC = "CHECK_TAG_VIA_PUBLIC"
export const DISABLE_PUBLIC_LINK = "DISABLE_PUBLIC_LINK"
export const SET_PASSWORD_PUBLIC_LINK = "SET_PASSWORD_PUBLIC_LINK"
export const UPDATE_UNREGISTERED_USER_TAG = "UPDATE_UNREGISTERED_USER_TAG"
export const REMOVE_GEM_FROM_SHARED_TAGS = "REMOVE_GEM_FROM_SHARED_TAGS"

// seo
export const UPDATE_TAG_SEO_DETAILS = "UPDATE_TAG_SEO_DETAILS"

export const DELETE_ALL_TAGS = "DELETE_ALL_TAGS"
export const DELETE_EMPTY_TAGS = "DELETE_EMPTY_TAGS"

export const SHARE_TAG_VIA_GROUP = "SHARE_TAG_VIA_GROUP"
export const UPDATE_TAG_GROUP_ACCESS = "UPDATE_TAG_GROUP_ACCESS"

export const CHECK_IS_TAG_PUBLIC = "CHECK_IS_TAG_PUBLIC"
export const REMOVE_SHARE_WITH_ME_TAG = "REMOVE_SHARE_WITH_ME_TAG"

export const GET_SUB_TAGS = "GET_SUB_TAGS"
export const SUB_TAG_PAGE = "SUB_TAG_PAGE"
export const ADD_SUB_TAG_DATA = "ADD_SUB_TAG_DATA"

export const GET_SHARED_TAGS_FILTER_COUNTS = "GET_SHARED_TAGS_FILTER_COUNTS"
export const GET_SHARED_TAGS_COLLECTIONS_COUNTS = "GET_SHARED_TAGS_COLLECTIONS_COUNTS"
export const GET_SHARED_TAGS_FILTERS_GEMS = "GET_SHARED_TAGS_FILTERS_GEMS"
export const GET_SHARED_TAGS_COLLECTIONS_GEMS = "GET_SHARED_TAGS_COLLECTIONS_GEMS"
export const GET_SHARED_TAGS_PUBLIC_SIDEBAR = "GET_SHARED_TAGS_PUBLIC_SIDEBAR"
