"use client"
import { LinkIcon,
         CodeBracketIcon,
         HeartIcon, 
         VideoCameraIcon,
         PhotoIcon,
         SpeakerWaveIcon,
         DevicePhoneMobileIcon,
         ShoppingBagIcon,
         FilmIcon,
         BookOpenIcon}                  from "@heroicons/react/24/outline";
import { RiEdit2Line,
         RiArticleLine,
         RiScreenshot2Line,
         RiRobotLine,
         RiDoubleQuotesL,
         RiTextSpacing,
         RiAlignCenter
       }                                from 'react-icons/ri'
import { TbSocial }                     from 'react-icons/tb'
import { TfiWrite }                     from 'react-icons/tfi'
import { BiNotepad,
         BiUserCircle }                 from "react-icons/bi";
import { AiOutlineFilePdf }             from "react-icons/ai";
import session                          from "./session";
import { LiaBlogSolid } from "react-icons/lia";

export const MEDIA_TYPES_ICONS_OBJ = {
    Link: {
      id: "links",
      children: [],
      title: "Link",
      link: `/u/${session.username}/filters/link?type=Link`,
      icon: <LinkIcon className="h-5 w-5" />,
      count: 0,
    },
    Code: {
      id: "code",
      children: [],
      title: "Code",
      link: `/u/${session.username}/filters/code?type=Code`,
      icon: <CodeBracketIcon className="h-5 w-5" />,
      count: 0,
    },
    Highlight: {
      id: "highlights",
      children: [],
      title: "Highlight",
      link: `/u/${session.username}/filters/highlight?type=Highlight`,
      icon: <RiEdit2Line className="h-5 w-5" />,
      count: 0,
    },
    Favourites: {
      id: "favourites",
      children: [],
      title: "Favourites",
      link: `/u/${session.username}/filters/favourites?type=Favourites`,
      icon: <HeartIcon className="h-5 w-5" />,
      count: 0,
    },
    Article: {
      id: "articles",
      children: [],
      title: "Article",
      link: `/u/${session.username}/filters/article?type=Article`,
      icon: <RiArticleLine className="h-5 w-5" />,
      count: 0,
    },
    PDF: {
      id: "pdf",
      children: [],
      title: "PDF",
      link: `/u/${session.username}/filters/pdf?type=PDF`,
      icon: <AiOutlineFilePdf className="h-5 w-5" />,
      count: 0,
    },
    Video: {
      id: "videos",
      children: [],
      title: "Video",
      link: `/u/${session.username}/filters/video?type=Video`,
      icon: <VideoCameraIcon className="h-5 w-5" />,
      count: 0,
    },
    Image: {
      id: "images",
      children: [],
      title: "Image",
      link: `/u/${session.username}/filters/image?type=Image`,
      icon: <PhotoIcon className="h-5 w-5" />,
      count: 0,
    },
    Audio: {
      id: "audio",
      children: [],
      title: "Audio",
      link: `/u/${session.username}/filters/audio?type=Audio`,
      icon: <SpeakerWaveIcon className="h-5 w-5" />,
      count: 0,
    },
    Screenshot: {
      id: "screenshot",
      children: [],
      title: "Screenshot",
      link: `/u/${session.username}/filters/screenshot?type=Screenshot`,
      icon: <RiScreenshot2Line className="h-5 w-5" />,
      count: 0,
    },
    'App': {
        id: "apps",
        children: [],
        title: "App",
        link: `/u/${session.username}/filters/app?type=App`,
        icon: <DevicePhoneMobileIcon className="h-5 w-5"/>,
        count:0
    },
    Product: {
      id: "products",
      children: [],
      title: "Product",
      link: `/u/${session.username}/filters/product?type=Product`,
      icon: <ShoppingBagIcon className="h-5 w-5" />,
      count: 0,
    },
    "Ai Prompt": {
      id: "aiPrompt",
      children: [],
      title: "Ai Prompt",
      link: `/u/${session.username}/filters/ai-prompt?type=Ai Prompt`,
      icon: <RiRobotLine className="h-5 w-5" />,
      count: 0,
    },
    Quote: {
      id: "quotes",
      children: [],
      title: "Quote",
      link: `/u/${session.username}/filters/quote?type=Quote`,
      icon: <RiDoubleQuotesL className="h-5 w-5" />,
      count: 0,
    },
    Note: {
      id: "notes",
      children: [],
      title: "Note",
      link: `/u/${session.username}/filters/note?type=Note`,
      icon: <BiNotepad className="h-5 w-5" />,
      count: 0,
    },
    Movie: {
      id: "movies",
      children: [],
      title: "Movie",
      link: `/u/${session.username}/filters/movie?type=Movie`,
      icon: <FilmIcon className="h-5 w-5" />,
      count: 0,
    },
    Profile: {
      id: "Profile",
      children: [],
      title: "Profile",
      link: `/u/${session.username}/filters/profile?type=Profile`,
      icon: <BiUserCircle className="h-5 w-5" />,
      count: 0,
    },
    Book: {
      id: "books",
      children: [],
      title: "Book",
      link: `/u/${session.username}/filters/book?type=Book`,
      icon: <BookOpenIcon className="h-5 w-5" />,
      count: 0,
    },
    SocialFeed: {
      id: "socialFeed",
      children: [],
      title: "SocialFeed",
      link: `/u/${session.username}/filters/socialfeed?type=SocialFeed`,
      icon: <TbSocial className="h-5 w-5" />,
      count: 0,
    },
    "Text Expander": {
      id: "textExpander",
      children: [],
      title: "Text Expander",
      link: `/u/${session.username}/filters/text-expander?type=Text Expander`,
      icon: <RiTextSpacing className="h-5 w-5" />,
      count: 0,
    },
    Citation: {
      id: "citation",
      children: [],
      title: "Citation",
      link: `/u/${session.username}/filters/Citation?type=Citation`,
      icon: <RiAlignCenter className="h-5 w-5" />,
      count: 0,
    },
    Testimonial: {
      id: "testimonial",
      children: [],
      title: "Testimonial",
      link: `/u/${session.username}/filters/Testimonial?type=Testimonial`,
      icon: <TfiWrite className="h-5 w-5" />,
      count: 0,
    },
    Blog: {
      id: "blog",
      children: [],
      title: "Blog",
      link: `/u/${session.username}/filters/Blog?type=Blog`,
      icon: <LiaBlogSolid className="h-5 w-5" />,
      count: 0,
    },
};