export const AUTHORIZED_UMAMI = "AUTHORIZED_UMAMI";
export const GET_WEBSITE = "GET_WEBSITE";
export const PAGE_VIEWS = "PAGE_VIEWS";
export const ACTIVE_USER = "ACTIVE_USER";
export const GET_WEBSITE_STATS = "GET_WEBSITE_STATS";
export const GET_WEBSITE_METRICS = "GET_WEBSITE_METRICS";