export const SEARCH_GEMS = "SEARCH_GEMS";
export const GET_BOOKMARK_BY_FILTERS = "GET_BOOKMARK_BY_FILTERS";
export const FETCH_GEMS_FILTERS = "FETCH_GEMS_FILTERS";
export const UPDATE_SCREENSHOT = "UPDATE_SCREENSHOT";
export const RESET_GEMS_FILTERS = "RESET_GEMS_FILTERS";

export const SET_CURRENT_GEM = "SET_CURRENT_GEM";
export const FETCH_TEXT_TO_SPEECH = "FETCH_TEXT_TO_SPEECH";
export const DELETE_HIGHLIGHT = "DELETE_HIGHLIGHT";
export const ADD_HIGHLIGHT = "ADD_HIGHLIGHT";
export const FETCH_URL_HIGHLIGHTS = "FETCH_URL_HIGHLIGHTS";
export const FETCH_DOMAIN_DETAILS = 'FETCH_DOMAIN_DETAILS'
export const SET_DOMAIN_DETAILS = 'SET_DOMAIN_DETAILS'
export const GET_TRANSCRIPT_URL = 'GET_TRANSCRIPT_URL'
export const GET_SINGLE_FILE = 'GET_SINGLE_FILE'
export const FETCH_ARTICLE = 'FETCH_ARTICLE'
export const DELETE_ALL_GEMS = 'DELETE_ALL_GEMS'
export const UPDATE_FILTER_COUNT = 'UPDATE_FILTER_COUNT'

// SEO details

export const UPDATE_GEM_SEO_DETAILS = "UPDATE_GEM_SEO_DETAILS";

// update usage count
export const UPDATE_USAGE_COUNT = "UPDATE_USAGE_COUNT";
export const GET_USAGE_COUNT = "GET_USAGE_COUNT"

export const CREATE_BLOG = "CREATE_BLOG";
export const UPDATE_BLOG = "UPDATE_BLOG";
export const PUBLISH_BLOG = "PUBLISH_BLOG";